services:
  frontend:
    image: dailmate-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    environment:
      - PORT=8000
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_PORT=${DB_PORT}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - PUBLIC_URL=${PUBLIC_URL}
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - ELEVENLABS_VOICE_ID=${ELEVENLABS_VOICE_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_FROM=${TWILIO_FROM}

  nginx:
    image: dailmate-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dailmate-nginx.rule=Host(`dailmate.webndevs.com`)"
      - "traefik.http.routers.dailmate-nginx.entrypoints=websecure"
      - "traefik.http.routers.dailmate-nginx.tls.certresolver=letsencrypt"
      - "traefik.http.services.dailmate-nginx.loadbalancer.server.port=80"
    depends_on:
      - frontend
      - server


